#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Find
version:      0.04
version_from: Find.pm
installdirs:  site
requires:
    File::Spec:                    0
    File::Find:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
